# Generated by Django 5.1.6 on 2025-02-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='product_pro_name_07d794_idx',
            old_name='product_pro_name_b60cd1_idx',
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='product_pro_status_dd7ee6_idx',
            old_name='product_pro_status_48d769_idx',
        ),
    ]
