# Generated by Django 5.1.6 on 2025-02-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='subcategory',
        ),
    ]
