# Generated by Django 5.1.6 on 2025-02-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_name_subcategory_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='(Gram)'),
        ),
    ]
