# Generated by Django 5.1.6 on 2025-02-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_products_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='(GRAM)', max_digits=10),
        ),
    ]
