# Generated by Django 5.1.6 on 2025-02-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_products_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AVAILABLE', 'Available'), ('OUT_OF_STOCK', 'Out_of_stock'), ('ARCHIVED', 'Archived')], max_length=16),
        ),
    ]
